<?php echo $this->getCategoryTree() ?>

<script>
    jQuery('div[data-tab="<?php echo $this->getBlockAlias() ?>"] span').attr('draggable', true);
    jQuery('div[data-tab="<?php echo $this->getBlockAlias() ?>"] span').on('dragstart', function(e){
        e.originalEvent.dataTransfer.setData('id', jQuery(e.target).data('id'));
        e.originalEvent.dataTransfer.setData('type', 'category');
    });
</script>

<style type="text/css">
    div[data-tab="<?php echo $this->getBlockAlias() ?>"] ul{
        margin-left: 1em;
    }
    div[data-tab="<?php echo $this->getBlockAlias() ?>"] > ul{
        margin-left: 0;
    }
    div[data-tab="<?php echo $this->getBlockAlias() ?>"] ul span{
        cursor: move;
    }
</style>