<script>
    jQuery('#cmsPageGrid_table tbody tr').attr('draggable', true);
    jQuery('#cmsPageGrid_table tbody tr').on('dragstart', function(e){
        e.originalEvent.dataTransfer.setData('id', parseInt(jQuery(e.target).attr('title').match(/page_id\/(\d+)/)[1]));
        e.originalEvent.dataTransfer.setData('type', 'cms');
    });
</script>

<style>
    div[data-tab="cms_page"] .content-header{
        display: none;
    }
</style>