<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
<script>jQuery.noConflict();</script>

<div class="menu-column">
    <h1>Manage Menu</h1>
    <p>Use the controls to setup a completely customised menu which will replace the default Magento category menu.</p>
    <form id="edit-menu-item" class="menu-form hide" action="<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/updateData') ?>" enctype="multipart/form-data" class="hide">
        <a class="cancel-edit">&nbsp;</a>
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <input type="hidden" name="id" value="">
        <label for="title">Title</label>
        <input type="text" name="title" value="">
        <label for="title">URL</label>
        <input type="text" name="url" value="">
        <label for="image">Image</label>
        <input type="file" name="image">
        <input type="checkbox" name="is_html" id="edit:is_html">
        <label for="edit:is_html">HTML Block</label>
        <div class="html hide">
            <label for="html">HTML</label>
            <textarea name="html" rows="8"></textarea>
        </div>
        <div class="button-set">
            <a class="update">Update</a>
            <a class="remove-image">Remove Image</a>
            <a class="delete">Delete</a>
        </div>
    </form>
    <div id="edge-menu">
        <span class="drag-notice">Drag and drop here to create top level menu item.</span>
    </div>
</div>
<div class="setup-column">
    <div class="tabs">
        <div class="control">
            <?php foreach ($this->getChild() as $alias => $block): ?>
                <span data-tab="<?php echo $alias ?>">
                    <?php echo $block->getTitle() ?>
                </span>
            <?php endforeach; ?>
        </div>
        <div class="content">
            <?php foreach ($this->getChild() as $alias => $block): ?>
                <div data-tab="<?php echo $alias ?>">
                    <?php echo $this->getChildHtml($alias) ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<script>
    jQuery.noConflict();
    (function($){

        var menu = $('#edge-menu');
        var data = <?php echo json_encode($this->getMenu()->getData()) ?>;
        if(data.length > 0)
            data.each(function(item){
                var div = $('<div>', {'data-id': item.id, 'data-type': item.type, draggable: true});
                div.append($('<i>', {class: 'sort-up'}));
                div.append($('<i>', {class: 'sort-down'}));
                div.append($('<span>').html(item.title));
                if(item.image)
                    div.append($('<img>', {src: '/media/' + item.image, alt: item.title}));

                if(!item.parent)
                    menu.append(div);
                else
                    menu.find('div[data-id="' + item.parent + '"]').append(div);
            });

        menu.on('dragstart', 'div[data-id]', function(e){
            e.originalEvent.dataTransfer.setData('id', $(e.target).data('id'));
            e.originalEvent.dataTransfer.setData('sorting', true);
        });
        menu.on('dragleave', 'span', function(e){
            $('*').removeClass('dropover');
        });
        menu.on('dragover', 'span', function(e){
            e.preventDefault();
            $(e.target).addClass('dropover');
        });
        menu.on('drop', 'span', function(e){
            e.preventDefault();

            var parent = null;
            if($(e.target).closest('div').data('id'))
                parent = $(e.target).closest('div').data('id');

            if(e.originalEvent.dataTransfer.getData('sorting')){
                var values = {
                    id: e.originalEvent.dataTransfer.getData('id'),
                    parent: parent,
                    'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
                };
                $.post('<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/changeParent') ?>?isAjax=true', values, reloadPage);
            }
            else{
                var values = {
                    id: e.originalEvent.dataTransfer.getData('id'),
                    type: e.originalEvent.dataTransfer.getData('type'),
                    parent: parent,
                    'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
                };
                $.post('<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/dataJson') ?>?isAjax=true', values, insertData);
            }
        });

        function insertData(insertData){
            var parent = insertData.parent || null;

            if(data.length < 1)
                insertData.sort = 1;
            else{
                // Work out sort based on other elements
                var sort = 1;
                data.each(function(item){
                    if(item.parent === parent && parseInt(item.sort) >= sort)
                        sort = parseInt(item.sort)+1;
                });
                insertData.sort = sort;
            }

            var values = {
                data: insertData,
                'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
            };

            $.post('<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/insertData') ?>?isAjax=true', values, reloadPage);
        }


        $('#edge-menu').on('click', '.sort-up', function(e){
            var values = {
                id: $(e.target).closest('div').data('id'),
                'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
            };
            $.post('<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/sortUp') ?>?isAjax=true', values, reloadPage);
        });
        $('#edge-menu').on('click', '.sort-down', function(e){
            var values = {
                id: $(e.target).closest('div').data('id'),
                'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
            };
            $.post('<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/sortDown') ?>?isAjax=true', values, reloadPage);
        });

        $('input[name="is_html"]').on('click', function(e){
            if($(e.target).is(':checked'))
                $(e.target).siblings('.html').removeClass('hide');
            else
                $(e.target).siblings('.html').addClass('hide');
        });

        $('span[data-tab]').on('click', function(e){
            $('[data-tab]').removeClass('active');
            $(e.target).addClass('active');
            $('div[data-tab="' + $(e.target).data('tab') + '"]').addClass('active');
            window.localStorage.setItem('tab', $(e.target).data('tab'));
        });
        var activeTab = window.localStorage.getItem('tab');
        if(!activeTab)
            activeTab = $('.tabs .control span[data-tab]:first-child').data('tab');
        $('span[data-tab="' + activeTab + '"]').trigger('click');

        $('#edge-menu div[data-id] > span').on('click', function(e){
            $.ajax({
                url: '<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/getItem') ?>',
                data: {
                    id: $(e.target).closest('div').data('id')
                },
                success: function(data){
                    $('#edit-menu-item input[name="id"]').val(data.id);
                    $('#edit-menu-item input[name="title"]').val(data.title);
                    $('#edit-menu-item input[name="url"]').val(data.url);
                    $('#edit-menu-item textarea[name="html"]').val(data.html);
                    $('#edit-menu-item input[name="is_html"]').prop('checked', data.is_html==="1");
                    if(data.is_html==="1")
                        $('#edit-menu-item .html').removeClass('hide');
                    else
                        $('#edit-menu-item .html').addClass('hide');

                    if($(e.target).next('img').length > 0)
                        $(e.target).next('img').after($('#edit-menu-item').removeClass('hide').removeClass('no-image'));
                    else
                        $(e.target).after($('#edit-menu-item').removeClass('hide').addClass('no-image'));
                }
            });
        });
        $('#edit-menu-item .cancel-edit').on('click', function(){
            $('#edit-menu-item input[name="id"]').val(null);
            $('#edit-menu-item').addClass('hide');
        });
        $('#edit-menu-item .remove-image').on('click', function(){
            if(!window.confirm("Are you sure you want to remove this image?"))
                return;

            var values = {
                id: $('#edit-menu-item input[name="id"]').val(),
                'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
            };
            $.post('<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/deleteImage') ?>', values, reloadPage);
        });
        $('#edit-menu-item .update').on('click', function(){
            $.ajax({
                url: $('#edit-menu-item').attr('action'),
                type: 'POST',
                data: new FormData($('#edit-menu-item')[0]),
                processData: false,
                contentType: false,
                success: reloadPage
            });
        });
        $('#edit-menu-item .delete').on('click', function(){
            if(!window.confirm("Are you sure you want to delete this item? Any children will also be deleted."))
                return;

            var values = {
                id: $('#edit-menu-item input[name="id"]').val(),
                'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
            };
            $.post('<?php echo Mage::helper('adminhtml')->getUrl('menu/admin/deleteData') ?>', values, reloadPage);
        });

        function reloadPage(){
            window.location.reload();
        }
    })(jQuery);
</script>