<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
<script>jQuery.noConflict();</script>
<div class="menu-columns">
    <header>
        <div class="left">
            <h1><?php echo Mage::helper('adminhtml')->__('Menu') ?></h1>
        </div>
        <div class="right">
            <div class="tabs">
            <?php foreach ($this->getChild() as $alias => $block): ?>
                <span data-tab="<?php echo $alias ?>">
                    <?php echo $block->getTitle() ?>
                </span>
            <?php endforeach; ?>
            </div>
        </div>
    </header>
    <article>
        <div class="left">
            <ul data-menu="<?php echo htmlspecialchars(Mage::helper('core')->jsonEncode($this->getMenu()->getData())) ?>"
                data-form-key="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
                data-website="<?php echo Mage::app()->getRequest()->getParam('website') ?>"
                data-url="<?php echo Mage::getUrl("adminhtml") . 'menu/' ?>"></ul>
        </div>
        <div class="right">
            <div class="creator">
            <?php foreach ($this->getChild() as $alias => $block): ?>
                <div data-tab="<?php echo $alias ?>">
                    <?php echo $this->getChildHtml($alias) ?>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </article>
</div>
