<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
<script>jQuery.noConflict();</script>
<?php
    $jsSetupConfig = 'Wysiwyg_Edit_Item';
    $editorId = 'html';
    $wysiwygConfig = Mage::getSingleton('cms/wysiwyg_config')->getConfig();
?>
<div class="menu-column">
    <h1><?php echo Mage::helper('adminhtml')->__('Manage Menu') ?></h1>
    <p><?php echo Mage::helper('adminhtml')->__('Use the controls to setup a completely customised menu which will replace the default Magento category menu.') ?></p>
    <form id="edit-menu-item" class="menu-form hide" action="<?php echo Mage::helper('adminhtml')->getUrl('*/*/updateData') ?>" enctype="multipart/form-data" class="hide">
        <a class="cancel-edit">&nbsp;</a>
        <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>">
        <input type="hidden" name="id" value="">
        <table class="original-details">
            <tr>
                <th>Type</th>
                <td data-attr="type"></td>
            </tr>
            <tr>
                <th>ID</th>
                <td data-attr="entity_id"></td>
            </tr>
        </table>
        <label for="edit:title">Title</label>
        <input type="text" name="title" id="edit:title" value="">
        <label for="edit:url">URL</label>
        <input type="text" name="url" id="edit:url" value="">
        <label for="edit:image">Image</label>
        <input type="file" name="image" id="edit:image">
        <input type="checkbox" name="is_html" id="edit:is_html">
        <label for="edit:is_html">HTML Block</label>
        <div class="html hide">
            <label for="edit:html">HTML</label>
            <div class="buttons-set">
                <button type="button" class="scalable show-hide" style="" id="toggle<?php echo $editorId ?>">
                    <span><span><span><?php echo $this->__('Show / Hide Editor') ?></span></span></span>
                </button>
            </div>
            <textarea id="<?php echo $editorId ?>" name="html" rows="8"></textarea>
        </div>
        <div class="button-set">
            <a class="update">Update</a>
            <a class="remove-image">Remove Image</a>
            <a class="delete">Delete</a>
        </div>
    </form>
    <div id="edge-menu">
        <span class="drag-notice">Drag and drop here to create top level menu item.</span>
    </div>
</div>
<div class="setup-column">
    <div class="tabs">
        <div class="control">
            <?php foreach ($this->getChild() as $alias => $block): ?>
                <span data-tab="<?php echo $alias ?>">
                    <?php echo $block->getTitle() ?>
                </span>
            <?php endforeach; ?>
        </div>
        <div class="content">
            <?php foreach ($this->getChild() as $alias => $block): ?>
                <div data-tab="<?php echo $alias ?>">
                    <?php echo $this->getChildHtml($alias) ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<script>
    var $j = jQuery;
    var menu = $j('#edge-menu');
    var data = <?php echo json_encode($this->getMenu()->getData()) ?>;
    if(data.length > 0)
        data.each(function(item){
            var div = $j('<div>', {'data-id': item.id, 'data-type': item.type, draggable: true});
            div.append($j('<i>', {class: 'sort-up'}));
            div.append($j('<i>', {class: 'sort-down'}));
            div.append($j('<span>', {class: 'item-title'}).html(item.title));
            if(item.image)
                div.append($j('<img>', {class: 'item-image', src: '/media/' + item.image, alt: item.title}));

            if(!item.parent)
                menu.append(div);
            else
                menu.find('div[data-id="' + item.parent + '"]').append(div);
        });

    menu.on('dragstart', 'div[data-id]', function(e){
        e.originalEvent.dataTransfer.setData('id', $j(e.target).data('id'));
        e.originalEvent.dataTransfer.setData('sorting', true);
    });
    menu.on('dragleave', 'span', function(e){
        $j('*').removeClass('dropover');
    });
    menu.on('dragover', 'span', function(e){
        e.preventDefault();
        $j(e.target).addClass('dropover');
    });
    menu.on('drop', 'span', function(e){
        e.preventDefault();

        var parent = null;
        if($j(e.target).closest('div').data('id'))
            parent = $j(e.target).closest('div').data('id');

        if(e.originalEvent.dataTransfer.getData('sorting')){
            var values = {
                id: e.originalEvent.dataTransfer.getData('id'),
                parent: parent,
                'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
            };
            $j.post('<?php echo Mage::helper('adminhtml')->getUrl('*/*/changeParent') ?>?isAjax=true', values, reloadPage);
        }
        else{
            var values = {
                id: e.originalEvent.dataTransfer.getData('id'),
                type: e.originalEvent.dataTransfer.getData('type'),
                parent: parent,
                'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
            };
            $j.post('<?php echo Mage::helper('adminhtml')->getUrl('*/*/dataJson') ?>?isAjax=true', values, insertData);
        }
    });

    function insertData(insertData){
        var parent = insertData.parent || null;

        if(data.length < 1)
            insertData.sort = 1;
        else{
            // Work out sort based on other elements
            var sort = 1;
            data.each(function(item){
                if(item.parent === parent && parseInt(item.sort) >= sort)
                    sort = parseInt(item.sort)+1;
            });
            insertData.sort = sort;
        }

        var values = {
            data: insertData,
            'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
        };

        $j.post('<?php echo Mage::helper('adminhtml')->getUrl('*/*/insertData') ?>?isAjax=true', values, reloadPage);
    }


    $j('#edge-menu').on('click', '.sort-up', function(e){
        var values = {
            id: $j(e.target).closest('div').data('id'),
            'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
        };
        $j.post('<?php echo Mage::helper('adminhtml')->getUrl('*/*/sortUp') ?>?isAjax=true', values, reloadPage);
    });
    $j('#edge-menu').on('click', '.sort-down', function(e){
        var values = {
            id: $j(e.target).closest('div').data('id'),
            'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
        };
        $j.post('<?php echo Mage::helper('adminhtml')->getUrl('*/*/sortDown') ?>?isAjax=true', values, reloadPage);
    });

    $j('input[name="is_html"]').on('click', function(e){
        if($j(e.target).is(':checked'))
            $j(e.target).siblings('.html').removeClass('hide');
        else
            $j(e.target).siblings('.html').addClass('hide');
    });

    $j('span[data-tab]').on('click', function(e){
        $j('[data-tab]').removeClass('active');
        $j(e.target).addClass('active');
        $j('div[data-tab="' + $j(e.target).data('tab') + '"]').addClass('active');
        window.localStorage.setItem('tab', $j(e.target).data('tab'));
    });
    var activeTab = window.localStorage.getItem('tab');
    if(!activeTab)
        activeTab = $j('.tabs .control span[data-tab]:first-child').data('tab');
    $j('span[data-tab="' + activeTab + '"]').trigger('click');

    $j('#edge-menu div[data-id] > span').on('click', function(e){
        $j.ajax({
            url: '<?php echo Mage::helper('adminhtml')->getUrl('*/*/getItem') ?>',
            data: {
                id: $j(e.target).closest('div').data('id')
            },
            success: function(data){
                if(data.is_html==="1")
                    $j('#edit-menu-item .html').removeClass('hide');
                else
                    $j('#edit-menu-item .html').addClass('hide');

                if($j(e.target).next('img').length > 0)
                    $j(e.target).next('img').after($j('#edit-menu-item').removeClass('hide').removeClass('no-image'));
                else
                    $j(e.target).after($j('#edit-menu-item').removeClass('hide').addClass('no-image'));

                $j('#edit-menu-item input[name="id"]').val(data.id);
                $j('#edit-menu-item input[name="title"]').val(data.title);
                $j('#edit-menu-item input[name="is_html"]').prop('checked', data.is_html==="1");

                if(data.type === 'custom' && !data.entity_id){
                    $j('#edit-menu-item label[for="edit:url"]').show();
                    $j('#edit-menu-item input[name="url"]').val(data.url).attr('disabled', false).show();
                    $j('#edit-menu-item .original-details').hide();
                }else{
                    $j('#edit-menu-item label[for="edit:url"]').hide();
                    $j('#edit-menu-item input[name="url"]').val(null).attr('disabled', true).hide();
                    $j('#edit-menu-item .original-details').show();
                    $j('#edit-menu-item [data-attr]').each(function(){
                        $j(this).html(data[$j(this).data('attr')]);
                    });
                }

                tinyMCE.EditorManager.execCommand('mceRemoveEditor', true, '<?php echo $editorId ?>');
                $j('#edit-menu-item textarea[name="html"]').val(data.html);
                tinyMCE.EditorManager.execCommand('mceAddEditor', true, '<?php echo $editorId ?>');
            }
        });
    });
    $j('#edit-menu-item .cancel-edit').on('click', function(){
        $j('#edit-menu-item input[name="id"]').val(null);
        $j('#edit-menu-item').addClass('hide');
    });
    $j('#edit-menu-item .remove-image').on('click', function(){
        if(!window.confirm("Are you sure you want to remove this image?"))
            return;

        var values = {
            id: $j('#edit-menu-item input[name="id"]').val(),
            'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
        };
        $j.post('<?php echo Mage::helper('adminhtml')->getUrl('*/*/deleteImage') ?>', values, reloadPage);
    });
    $j('#edit-menu-item .update').on('click', function(){
        tinyMCE.triggerSave();
        $j.ajax({
            url: $j('#edit-menu-item').attr('action'),
            type: 'POST',
            data: new FormData($j('#edit-menu-item')[0]),
            processData: false,
            contentType: false,
            success: reloadPage
        });
    });
    $j('#edit-menu-item .delete').on('click', function(){
        if(!window.confirm("Are you sure you want to delete this item? Any children will also be deleted."))
            return;

        var values = {
            id: $j('#edit-menu-item input[name="id"]').val(),
            'form_key': "<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"
        };
        $j.post('<?php echo Mage::helper('adminhtml')->getUrl('*/*/deleteData') ?>', values, reloadPage);
    });

    function reloadPage(){
        window.location.reload();
    }
</script>
<script type="text/javascript">
    //<![CDATA[
        openEditorPopup = function(url, name, specs, parent) {
            if ((typeof popups == "undefined") || popups[name] == undefined || popups[name].closed) {
                if (typeof popups == "undefined") {
                    popups = new Array();
                }
                var opener = (parent != undefined ? parent : window);
                popups[name] = opener.open(url, name, specs);
            } else {
                popups[name].focus();
            }
            return popups[name];
        };

        closeEditorPopup = function(name) {
            if ((typeof popups != "undefined") && popups[name] != undefined && !popups[name].closed) {
                popups[name].close();
            }
        };

        var <?php echo $jsSetupConfig ?> = new tinyMceWysiwygSetup('<?php echo $editorId ?>', <?php echo Mage::helper('core')->jsonEncode($wysiwygConfig) ?>);
        Event.observe(window, "load", <?php echo $jsSetupConfig ?>.setup.bind(<?php echo $jsSetupConfig ?>, "exact"));
        editorFormValidationHandler = <?php echo $jsSetupConfig ?>.onFormValidation.bind(<?php echo $jsSetupConfig ?>);
        Event.observe("toggle<?php echo $editorId ?>", "click", <?php echo $jsSetupConfig ?>.toggle.bind(<?php echo $jsSetupConfig ?>));
        varienGlobalEvents.attachEventHandler("formSubmit", editorFormValidationHandler);
        varienGlobalEvents.attachEventHandler("tinymceBeforeSetContent", <?php echo $jsSetupConfig ?>.beforeSetContent.bind(<?php echo $jsSetupConfig ?>));
        varienGlobalEvents.attachEventHandler("tinymceSaveContent", <?php echo $jsSetupConfig ?>.saveContent.bind(<?php echo $jsSetupConfig ?>));
        varienGlobalEvents.clearEventHandlers("open_browser_callback");
        varienGlobalEvents.attachEventHandler("open_browser_callback", <?php echo $jsSetupConfig ?>.openFileBrowser.bind(<?php echo $jsSetupConfig ?>));
    //]]>
</script>