<div class="switcher">
    <label for="select-website"><?php echo $this->__('Select Website:') ?></label>
    <select id="select-website" title="<?php echo $this->__('Select Website') ?>" onchange="window.location.href=this.value">
        <option value="<?php echo Mage::helper('adminhtml')->getUrl('*/*/*') ?>"><?php echo $this->__('All Websites') ?></option>
        <?php foreach (Mage::app()->getWebsites() as $website): ?>
            <option value="<?php echo Mage::helper('adminhtml')->getUrl('*/*/*', array('website' => $website->getId())) ?>"<?php if ($website->getId() === $this->getRequest()->getParam('website')) echo ' selected="selected"'; ?>>
                <?php echo $this->htmlEscape($website->getName()) ?>
            </option>
        <?php endforeach; ?>
    </select>
</div>