<form id="custom-link-form" enctype="multipart/form-data">
    <input type="hidden" name="type" value="custom">
    <div>
        <label for="title">Title</label>
        <input type="text" name="title" value="">
    </div>
    <div>
        <label for="title">URL</label>
        <input type="text" name="url" value="">
    </div>
    <div>
        <label for="image">Image</label>
        <input type="file" name="image">
    </div>
    <div>
        <label for="create:is_html">HTML Block</label>
        <input type="checkbox" name="is_html" id="create:is_html">
    </div>
    <div class="html hide">
        <label for="html">HTML</label>
        <textarea name="html" id="html-custom-link"></textarea>
    </div>
    <button type="button" class="drag-create" draggable="true">&larr; Drag to Create</button>
</form>